package enums;

public enum MovimentoPlayer {
	CAINDO,
	SUBINDO,
	POUSANDO,
	ANDANDO,
	PARANDO,
	ATACANDO,
	RESPIRANDO,
	RESPIRANDO_EM_COMBATE,
	INVESTINDO,

	HABILIDADE_POSTURA_OFENSIVA,
	HABILIDADE_POSTURA_DEFENSIVA,
	HABILIDADE_ENERGIZAR,
	HABILIDADE_POSTURA_CALMA,
	HABILIDADE_POSTURA_FIRME,
	HABILIDADE_TEMPESTADE_ELETRICA,
	HABILIDADE_POSTURA_SELVAGEM
}
